### ISSUE TITLE
Parsing Data from gentool.net/data

### ISSUE THREAD

**Issue by ra-97** [realpoke/genranks#3]
It turns out that traversing and accessing game replay info is pretty straightforward.

As the website is structured like a directory tree, we can just use patterns in order to read the links corresponding to each level in that directory tree.

For instance, moving from the root directory to a replay info text file will follow the following path:

- https://www.gentool.net/data/zh/
- https://www.gentool.net/data/zh/2023_06_June/
- https://www.gentool.net/data/zh/2023_06_June/20_Tuesday/ 
- https://www.gentool.net/data/zh/2023_06_June/20_Tuesday/%5bOoE%5dExCaL_135E11FB6002/
- https://www.gentool.net/data/zh/2023_06_June/20_Tuesday/%5bOoE%5dExCaL_135E11FB6002/14-39-51_2_OoEExCaL_OoEViViD.txt

Then, the file can be easily read and parsed for info.

At first we will need to traverse the entire directory starting at some starting date in order to populate the initial rankings, ELOs and so on for all players, then we can rely on a cronjob that keeps checking a number of times every day and keeps track of the latest datetime a check was made so that we end up reading the latest data after.

I am not sure where exactly we could know for sure if player A won against player B and so on yet.

This has been tested on a separate Jupyter notebook and seems to be working just fine.

**Comment by realpoke** [comment]
Sounds good, we should just do a random winner for now. Since we need to parse the replay to guess who won.

Using the [HTTP Client](https://laravel.com/docs/10.x/http-client) to look at the links, and then using REGEX or something similar to get the user ids, map, and more.

Its already setup to run a command twice a day, so you can code this logic in [this](https://github.com/realpoke/genranks/blob/8f957aaa48dedb2f356cf3373090d589a9c0a5ad/app/Console/Commands/GenTool.php#LL26C29-L26C29) command file!

You will have to create the game, with the game model. And check if the user exists and if not create them with a random safe email and password. Then assign them to the game with their army info etc.

**Comment by realpoke** [comment]
I just did a test using the HTTP client as mentioned above.
So adding the `use Illuminate\Support\Facades\Http;` facade and using that client.

`$this->info(Http::get('https://www.gentool.net/data/zh/2023_06_June/01_Thursday/'));`

This returns everything from the page, that we can then read and get other links that we can then also get and read until we get to the replays and txt files!

**Comment by realpoke** [comment]
One thing to note, is that we should only scrape the newest data back till last time we scraped. So we don't get duplicates, and we need something special if it's the first scrape we do, maybe?

**Comment by ra-97** [comment]
> One thing to note, is that we should only scrape the newest data back till last time we scraped. So we don't get duplicates, and we need something special if it's the first scrape we do, maybe?

I think we can just run the scrapper until it finished scrapping the directory that has the same date as today it first gets run, then it terminates.

But I think that we still need something in order to keep track of the last scrapping date.

**Comment by realpoke** [comment]
Get the latest game date. Since that's the last game, we fetched?

**Comment by ra-97** [comment]
> Get the latest game date. Since that's the last game, we fetched?

Yeah I think that works too 👍

**Comment by realpoke** [comment]
Also, if there are no games yet, then it's the first scrape we do. That's the way to check if it's the first scrape or not.

**Comment by ra-97** [comment]
I think we should run the first one manually, then it will do its job automatically, especially when the first one can possibly take a very long time. Once we see that we are getting the data we want and populating the tables we can then run the cron.

**Comment by realpoke** [comment]
It's the exact same command the job is scheduling. So just run the command, since it's the same. And we might want to have no overlapping of jobs, too. But will see about that later I think.

**Comment by realpoke** [comment]
We found the way of parsing the replays, applying it into the gentool fetch command!

**Comment by realpoke** [comment]
This is pretty much implemented now, we just assign a random winner for now. But all in this issue is pretty much done!
